# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headImg', models.CharField(max_length=100)),
                ('bgcolor', models.CharField(max_length=100)),
                ('opicaty', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
