# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-09 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_banner_opicaty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
