# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('headImg', models.CharField(max_length=200)),
                ('zoom', models.CharField(max_length=20)),
                ('small', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
