# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='my_cart',
        ),
    ]
